### PR TITLE
Sort by nested field

### PR DESCRIPTION
**Pull request by ClarenceL**
We properly reference nested fields with a key such as 'a.b.d' for the key, however for sorting we don't do this, this is inconsistent.

Reused .get function from lib/reactive_table.js - probably should merge sort.js into reactive_table.js now since .get is declared twice

### CODE REVIEW

**Comment by aslagle** [comment]
Thanks! `get` could be a package-level variable (remove the `var`) so it can be used in other files. Maybe it should be in its own file, but leaving it in reactive_table.js is fine for now. I'm trying to slowly break up reactive_table.js and reactive_table.html since they've gotten long and difficult to work with.

**Comment by ClarenceL** [comment]
Cool, let me know when you fix that. 

On my fork I've also added a fnSort function, the issue is for a virtual column I'm sometimes formatting the return value from fn, sortByValue doesn't work and I need a specific sorting function.

Even better may be a formatter function like in highcharts, the result returned from fn is passed into formatter, but the fn return value is used for sorting.

**Comment by aslagle** [comment]
Thanks, this is merged. fnSort would be useful too but I'm not sure what the API should look like.

**Comment by vlasky** [comment]
Please merge ClarenceL's fnSort enhancement. My application requires sorting a list of task with priorities based on complex criteria, not just ordering by value. ClarenceL's implementation seems simple, concise and well-suited.

**Comment by aslagle** [comment]
I don't think there's a pr for it yet..

**Pull request merged**
