### PR TITLE
Added aldeed:tabular.

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by brylie** [comment]
Related issue: #10

**Comment by aslagle** [comment]
Thanks! I've been meaning to add tabular but I haven't had time to try it out myself. Let's see if aldeed responds to any of the issues before I deploy the update. I think many of them are supported in the datatables API, but I'm not sure if they'll work in tabular. If they do, we could change the datatables row to say it has full support for meteor integration via tabular instead of having a separate row.

**Comment by aldeed** [comment]
@aslagle @brylie It might be worth having separate rows for some of the Meteor datatables wrappers. For example, I went to great lengths to make tabular perform well with large datasets, with automatic pub/sub. But this isn't always the best solution, especially if you have a small number of docs that are already on the client. In that case, using a more basic datatables wrapper might allow you to use more of the filter/sort features on more columns (because filter/sort can happen against client data).

I'm hoping to address any tabular issues in the coming weeks. I've been insanely busy, but things are starting to calm down.

**Comment by aslagle** [comment]
Ok, I'll go with this for now. We can add more updates later :)

**Pull request merged**
