### PR TITLE
Ensure new fields can be reactively added to table

### LINKED ISSUE #156: Adding or displaying columns on reactive reruns of tableSettings does not work
In my app, I use reactive table to display entries that might have a 'problematic' flag on them. The template that contains the table subscribes to the collection in an autorun function and iterates through all the entries, searching if any of them has the problematic flag on. This is strored as a boolean to a ReactiveVar, and this ReactiveVar is used to determine whether to show a 'problem description' column in the table at all:
```javascript
Template.tableContainer.created = function() {
    var that = this;
    this.problems = new ReactiveVar(false);
    this.autorun(function() {
        // Subscription etc here...
        // ....
        var problems = false;
        cursor.forEach(function(item) {
            if (!problems && item.problematic)
                problems = true;
        });
        that.problems.set(problems);
    });
});
Template.tableContainer.helpers({
    tableSettings: function() {
        var fields = { ... };
        if (Template.instance().problems.get())
            fields.unshift({label: 'Problem description', ...});
        return {fields: fields, ....};
    }
});
```
Now, if problematic items are found, then the **last column disappears**. After some considerable debugging effort I *think* I figured out what happens here: As the table settings helper is run the first time, problematic is false (default value), since the items are not loaded yet. After the items are loaded and the autorun has been ran, the table settings helper immediately re-runs, this time adding the problem description column properly. **But** as the reactive table setup function caches the visibleFields-array in the context, it is not updated, even though the fields-array is. Thus **reactively increasing the number of visible fields has no effect on the actual number of fields shown.**

So the culprit, as far as I can tell, are these rows: (reactive_table.js, rows 192 - 198)
```javascript
var visibleFields = [];
_.each(fields, function (field, i) {
    if (!field.hidden || (_.isFunction(field.hidden) && !field.hidden())) {
        visibleFields.push(i);
    }
});
context.visibleFields = (!_.isUndefined(oldContext.visibleFields) && !_.isEmpty(oldContext.visibleFields)) ? oldContext.visibleFields : new ReactiveVar(visibleFields);
```
Where the last row loads visibleFields from cache if it is set and not empty, regardless of its value. I think this could be simply fixed, for example, by comparing the old visible fields with the new value and setting the new value if they differ. **Or did I miss something?**

### PR DESCRIPTION
**Pull request by rjsmith**
Instead of using the index of a field in the fields array to control
its visibility, use a dictionary of key / isVisible pairs.
This enables the code to detect if a field has been added reactively
and therefore set its default visibility correctly.

Note that this change now means that field key values must be unique
for column visibility control to work correctly (this wasn’t the case
before).  If there are non-unique key names, the visibility of the
first such field in the fields array will govern the visibility of all
of those fields.

This commit also includes corrected and added package tests related to
this change, and note in the README about consequences of non-unique
field keys.

Fixes #156

### CODE REVIEW

**Comment by aslagle** [comment]
Thanks! I like how it adds new fields but doesn't remove missing ones, in case you add one back later. It does bother me that it breaks column visibility for non-unique keys though. Maybe no one does that, but I could imagine you might want to have two columns that display one field in different formats and let the users toggle on the one they prefer. What would you think of requiring the key and label combination to be unique? If the label's a function or a template, it would be hard to get from an event handler, but I think it could be done.

**Comment by rjsmith** [comment]
Hi,
I think matching key+label combinations doesn't solve the fundamental constraint that the combination of both have to be unique for individual column visibility to work, where this uniqueness was not previously enforced by the library (same as with using the key alone).  I can't currently think of a way to handle reactive insertion of new fields whilst also correctly controlling visibility of existing individual columns without being able to uniquely identify each field in a way that is preserved across field additions (which is why the current index approach doesn't work).

I can only suggest introducing further complexity by having something like a 'enableDynamicFieldInsertion=true' flag, which , when true, enforces key uniqueness and uses this new key  - based mechanism, and when false falls back to the original index-based visibleFields implementation (but without support for dynamic field insertion).  By default, the flag is set to false, so that there is no change for existing implementations.  Double yuk, but only way to guarantee no breaking changes, given that key uniqueness has not been enforced previously.  What do you think?

**Comment by aslagle** [comment]
I think you're right, it's not worth making it fully backwards-compatible, and you do need a way to uniquely identify the columns. But I'm not sure which edge cases are sufficiently common that we should worry about them. 

For example, my team has a client that asked for year, month, and date as separate fields. I think they'll change their mind, but if I was going to implement that I'd store one date field and have three columns with the same key and different labels, so I don't think it's that unusual. There is an easy workaround of giving a fake key and using the real key to access the field from fn, so maybe it doesn't matter. 

On the other hand, two columns that have the same key and label but display the field differently would make for a very confusing table. Maybe you'd want to duplicate a column if you have a large number of columns that scroll horizontally, but in that case you're probably not using the visibility toggles.

**Comment by rjsmith** [comment]
Hmm. OK. I didn't really appreciate that the current `key` is really a 'key-of-a-collection-document'  (which can be duplicated in the use case of multiple date field columns you described above).  

So, in that case, I think we would have to introduce a new , optional, field attribute that does semantically define a guaranteed - unique field identity (which is orthogonal to a key into the underlying row model object).  `fieldId` perhaps? If users want the ability to control individual field visibility whilst also allowing dynamic field addition, they would have to specify a `fieldId' for every field.  Reactive-table could enforce rules that if one field has 'fieldId', then every field must have a `fieldId` and `fieldId` values must be unique.  The field visibility logic would then automatically use fieldId as the unique key, instead of field array index.  So effectively have two modes, but use the presence or absence of `fieldId`s as the 'switch'.  How does that sound as an idea .. happy to work on it to see what it looks like...)?

**Comment by aslagle** [comment]
That sounds great. You could default each fieldId to the array index in setup if none are provided, so the rest of the code would only have to use fieldIds.

**Comment by rjsmith** [comment]
Good idea :-)  OK, I'll fire up Sublime Text and try it out....

**Comment by rjsmith** [comment]
Hi,
I think I have resolved this now, by adopting the fieldId approach described above.  I also realised that the same problem (using field array index) hit the sortKey implementation, so I have altered that to use fieldId also.  
Commits include additional tests and a new section in the readme.

**Comment by aslagle** [comment]
Thanks, looks great! I'm publishing this now.

**Comment by rjsmith** [comment]
Thanks for publishing this.

**Pull request merged**
