### PR TITLE
add ability to sort columns via functions

### PR DESCRIPTION
**Pull request by sturmer-eha**
this is a small tweak that I've had to implement within the package in order to make one table with scattered schema to properly sort by the combined sum of different values

please feel free to reimplement, extend, or merge

### CODE REVIEW

**Comment by aslagle** [comment]
Thanks! This looks great, and it's cool someone from EHA is still using this package :)

There are two things I would change:
-  sortFn should have the same arguments as fn or it might be confusing.
- [this line](https://github.com/aslagle/reactive-table/blob/master/lib/reactive_table.js#L494) should be updated so it won't sort by value if there's a sortFn, but no sortByValue

**Comment by sturmer-eha** [comment]
Your origami cube and stars are still here by the way.
Built to last, just like the reactive-table.

I've updated the function's parameters and the line you've mentioned.
Might've done something which is not exactly you've meant, since I don't know the internals of the package that well. Please let me know if the logic inside of [that line](https://github.com/aslagle/reactive-table/pull/435/commits/9d3b222559eb657938aad64f650338e49798e2ec#diff-a1fb1352c54f1b11d1edb2c397bb0db4R494) needs to be altered.

Thanks for maintaining this package!

**Comment by aslagle** [comment]
Thanks for making the changes :)

I'm not totally sure what that line should be either, but I think I'd go with `field.sortByValue || (!field.fn && !field.sortFn)`. That would let you use sortFn without fn which could be useful, and if sortFn is undefined it does the same thing as before so it's more backwards-compatible.

**Comment by sturmer-eha** [comment]
I believe this should be good to go.

**Comment by aslagle** [comment]
Thanks :)

**Comment by sturmer-eha** [comment]
Likewise Ü

**Pull request merged**
