### PR TITLE
an option in publish settings to disable page count reactivity

### PR DESCRIPTION
**Pull request by s7dhansh**

### CODE REVIEW

**Comment by s7dhansh** [comment]
@aslagle What do you think about it?

**Comment by aslagle** [comment]
Thanks, this seems like a good option. Sorry for the delay. Do you mind fixing your indentation so it matches the rest of the file?

**Comment by s7dhansh** [comment]
Sorry for these multiple commits. Both github and Atom were suckers at doing the job. Finally had to resolvo to Sublime. It still appears a bit unindented in the diff, but in the editor it seems fine. I have no idea why.

**Comment by aslagle** [comment]
Thanks that looks better. I'll test it out tonight.

**Comment by s7dhansh** [comment]
Yeah sure. FYI, I am using it in my production.

**Comment by aslagle** [comment]
Published this in version 0.8.30. Thanks!

**Comment by s7dhansh** [comment]
cool thanks!

**Pull request merged**
