### PR TITLE
class="row" should not be present

### PR DESCRIPTION
**Pull request by fix**
it messes up with twitter-bootstrap, as it supposed that you nest your table in some col-*
It is also not homogenous with the table that has not the "row" class

### CODE REVIEW

**Comment by aslagle** [comment]
I'm fine with changing this, but the row class currently prevents the filter and column button from overlapping the table header in small Firefox windows, so that'll have to be fixed another way.

**Comment by fix** [comment]
Ok then "clearfix" would be more adapted then (as it won't mess up margins). Should i submit another PR?

**Comment by aslagle** [comment]
Sure, thanks!

**Comment by fix** [comment]
ok done!

**Comment by aslagle** [comment]
Released as version 0.5.13, thanks!

**Pull request merged**
